### ISSUE TITLE
Support Nested Folders with .excalidraw files

### ISSUE THREAD

**Issue by lucasavila00** [tommywalkie/excalidraw-cli#10]
**What I want:**

Take this repository as example: https://github.com/lucasavila00/excalidraw-cli-nested

It has a docs folder with another nested folder.
In the root docs folder I have .excalidraw files and in the nested folder I have more .excalidraw files. : https://github.com/lucasavila00/excalidraw-cli-nested/tree/master/docs

I'd like if this command worked https://github.com/lucasavila00/excalidraw-cli-nested/blob/master/package.json#L10 just like this.

This CLI should be able to traverse all nested folders and export the content they have.

**Why I want it:**

I want to create a generic, OSS, github action that makes sure you "compiled" the .excalidraw files before submitting a PR or that PR will fail.

Since now we have deterministic output we can just recompile everything and look for git diffs. If there is any diff then this PR will fail in CI and a warning telling the user that he forgot to compile the .excalidraw files will be shown.

I'd like to have 1 configuration for this action: a folder (possibily nested) where you store all you .excalidraw files (or possibly no configuration and this CLI traverses the whole repository file tree?)

Currently this generic, OSS action is impossible since I have to know all folders that have .excalidraw files and configure them...

**Comment by lucasavila00** [comment]
This idea is inspired by this workflow of nbdev by the way: https://github.com/fastai/nbdev#using-nbdev-as-part-of-your-ci

**Comment by tommywalkie** [comment]
@lucasavila00 Hi ! Thanks for the submission ! 😄 
I can totally understand why you would need it. Actually, listing `.excalidraw` files in nested folders is [a planned feature](https://github.com/tommywalkie/excalidraw-cli/projects/1#card-40760158). this will be the first step which will hopefully lead to the mentionned desired feature.

Some proper testing/error handling still needs to be implemented before adding this new feature, primarily for stability concerns but also for avoiding confusing behaviours [like this one](https://github.com/tommywalkie/excalidraw-cli/issues/9).

**Comment by tommywalkie** [comment]
@lucasavila00 New feature added as of https://github.com/tommywalkie/excalidraw-cli/commit/da5247c34a7290d0ee2e48a3b53afe2ef792243e and `0.4.3` 👍
