### ISSUE TITLE
Can't run "excalidraw-cli" npm script on Linux

### ISSUE THREAD

**Issue by lucasavila00** [tommywalkie/excalidraw-cli#2]
If you clone the repository and build it with "prepack && postpack" then try to run with "excalidraw-cli" then it won't run because of permission issues.

Run `sudo chmod -R 777 bin/run` to fix it

I really don't know how to make it automatic :/
I think this can be closed too as it's something simple but it's nice to have it here so that users find it if they need.

Search terms:
$ ./bin/run
/bin/sh: 1: ./bin/run: Permission denied

**Comment by tommywalkie** [comment]
@lucasavila00 Apparently, adding `sudo` in Ubuntu [solves the issue](https://github.com/tommywalkie/excalidraw-cli/runs/807657328?check_suite_focus=true#step:4:1) on ![Github Actions](https://badgen.net/badge/Github%20Actions/Ubuntu%2018.04/DD4814?icon=github)

https://github.com/tommywalkie/excalidraw-cli/blob/eaed48874b539bfe12990906c182f61ebb49b9c9/.github/workflows/test.yml#L26

But still, would be interested to look deeper into Oclif docs if there is something about it. 
FWIW `excalidraw-cli` CLI system is based on Oclif.

**Comment by lucasavila00** [comment]
The problem happens only when cloning for development, it installed fine from NPM.

**Comment by tommywalkie** [comment]
Renamed issue title to "_Can't run "excalidraw-cli" npm script on Linux_" for clarity.

**Comment by tommywalkie** [comment]
@lucasavila00 This is now fixed as of https://github.com/tommywalkie/excalidraw-cli/commit/b3f6a22b1878187f74d0aaf7c95e84975bab0939 which added a [**Contributing**](https://github.com/tommywalkie/excalidraw-cli#contributing) section in the README and replaced the current NPM script with the following one which uses Node instead. 👍 
```diff
-  "excalidraw-cli": "./bin/run"
+  "excalidraw-cli": "node ./bin/run"
```

**Comment by lucasavila00** [comment]
That Contributing section really helps, thanks :)
