### ISSUE TITLE
getFontFamilyFromId can't handle absence of fontFamily

### ISSUE THREAD

**Issue by lucasavila00** [tommywalkie/excalidraw-cli#4]
This is the same kind of issue as with #1 I guess.
The file I sent in #1 will return undefined for [getFontFamilyFromId](https://github.com/tommywalkie/excalidraw-cli/blob/master/src/renderer.js#L136) and the [ctx.font setter won't accept the value](https://github.com/tommywalkie/excalidraw-cli/blob/master/src/renderer.js#L285) and keep using the old one.

It won't break anything but it will not read the font I wanted to use.

**Comment by tommywalkie** [comment]
Might be able to fix all these issues with https://github.com/tommywalkie/excalidraw-cli/pull/3 if we try to fix the `getFontFamilyFromId` method and your PR's `getFontSise` method. Just need a bit of time and I'll look at it. 😄

**Comment by tommywalkie** [comment]
This has been fixed after merging #3 and commiting https://github.com/tommywalkie/excalidraw-cli/commit/6c94873d184195dacd0ae59941532dd81fad5179 which is the first step to some reactoring process on the home-made renderer.

Closing the issue. Thanks again @lucasavila00 for the PR. 👍

**Comment by tommywalkie** [comment]
The fix is now available as of `@tommywalkie/excalidraw-cli@0.3.6` NPM package version. 📣

**Comment by lucasavila00** [comment]
Thanks :)
